### ISSUE TITLE
Build failed with Postgres 17

### ISSUE THREAD

**Issue by shuaitian-git** [postgrespro/rum#146]
Need to refactor the code towards PG17

Error message:

src/rumsort.c: In function ‘rum_tuplesort_putrum’:
src/rumsort.c:496:9: error: too few arguments to function ‘tuplesort_puttuple_common’
  496 |         tuplesort_puttuple_common(state, &stup, false);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/postgresql/17/include/server/nodes/execnodes.h:49,
                 from /usr/lib/postgresql/17/include/server/executor/execdesc.h:18,
                 from /usr/lib/postgresql/17/include/server/executor/executor.h:17,
                 from src/rumsort.c:23:
/usr/lib/postgresql/17/include/server/utils/tuplesort.h:379:13: note: declared here
  379 | extern void tuplesort_puttuple_common(Tuplesortstate *state,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
src/rumsort.c: In function ‘rum_tuplesort_putrumitem’:
src/rumsort.c:514:9: error: too few arguments to function ‘tuplesort_puttuple_common’
  514 |         tuplesort_puttuple_common(state, &stup, false);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/postgresql/17/include/server/nodes/execnodes.h:49,
                 from /usr/lib/postgresql/17/include/server/executor/execdesc.h:18,
                 from /usr/lib/postgresql/17/include/server/executor/executor.h:17,
                 from src/rumsort.c:23:
/usr/lib/postgresql/17/include/server/utils/tuplesort.h:379:13: note: declared here
  379 | extern void tuplesort_puttuple_common(Tuplesortstate *state,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [<builtin>: src/rumsort.o] Error 1
Error on or near line 44: x; exiting with status 1
Error: Process completed with exit code 1.

**Comment by sokolcati** [comment]
Hi!
RUM was updated to 17 PostgreSQL in [commit cb1edffc5773](https://github.com/postgrespro/rum/commit/cb1edffc57736cd2a4455f8d0feab0d69928da25#diff-751d297005396b1e81c17bcc38c95e890ccfcc85cfbcc530cab76698d793798dR491)
Please, use [tag 1.3.14](https://github.com/postgrespro/rum/releases/tag/1.3.14) (or source code from master branch)

**Comment by shuaitian-git** [comment]
thanks, problem solved after updating to 1.3.14, could you create a new release for it?

**Comment by sokolcati** [comment]
It's not problem. But I'm curious - why is a release preferred over a tag?
