### ISSUE TITLE
PostgreSQL 11?

### ISSUE THREAD

**Issue by ArturFormella** [postgrespro/rum#48]
Hello!
I have the following error:

```
$sudo USE_PGXS=1 pgxn install rum

INFO: best version: rum 1.1.0
INFO: saving /tmp/tmp32u9l4/rum-1.1.0.zip
INFO: unpacking: /tmp/tmp32u9l4/rum-1.1.0.zip
INFO: building extension
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -pie -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal -I/usr/include/x86_64-linux-gnu -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o src/rumsort.o src/rumsort.c
In file included from /usr/include/postgresql/11/server/catalog/index.h:18:0,
                 from src/rumsort.c:129:
/usr/include/postgresql/11/server/nodes/execnodes.h:1849:2: error: unknown type name ‘TuplesortInstrumentation’
  TuplesortInstrumentation sinstrument[FLEXIBLE_ARRAY_MEMBER];
  ^
In file included from src/rumsort.c:138:0:
/usr/include/postgresql/11/server/utils/probes.h:10:21: fatal error: sys/sdt.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'src/rumsort.o' failed
make: *** [src/rumsort.o] Error 1
ERROR: command returned 2: make PG_CONFIG=/usr/bin/pg_config all
```

My pg_config:
```
root@DKXP:/home/a.formella# pg_config
BINDIR = /usr/lib/postgresql/11/bin
DOCDIR = /usr/share/doc/postgresql-doc-11
HTMLDIR = /usr/share/doc/postgresql-doc-11
INCLUDEDIR = /usr/include/postgresql
PKGINCLUDEDIR = /usr/include/postgresql
INCLUDEDIR-SERVER = /usr/include/postgresql/11/server
LIBDIR = /usr/lib/x86_64-linux-gnu
PKGLIBDIR = /usr/lib/postgresql/11/lib
LOCALEDIR = /usr/share/locale
MANDIR = /usr/share/postgresql/11/man
SHAREDIR = /usr/share/postgresql/11
SYSCONFDIR = /etc/postgresql-common
PGXS = /usr/lib/postgresql/11/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/include' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/lib/x86_64-linux-gnu' '--libexecdir=/usr/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-icu' '--with-tcl' '--with-perl' '--with-python' '--with-pam' '--with-openssl' '--with-libxml' '--with-libxslt' '--with-tclconfig=/usr/lib/x86_64-linux-gnu/tcl8.6' '--with-includes=/usr/include/tcl8.6' 'PYTHON=/usr/bin/python' '--mandir=/usr/share/postgresql/11/man' '--docdir=/usr/share/doc/postgresql-doc-11' '--sysconfdir=/etc/postgresql-common' '--datarootdir=/usr/share/' '--datadir=/usr/share/postgresql/11' '--bindir=/usr/lib/postgresql/11/bin' '--libdir=/usr/lib/x86_64-linux-gnu/' '--libexecdir=/usr/lib/postgresql/' '--includedir=/usr/include/postgresql/' '--with-extra-version= (Ubuntu 11.0-1.pgdg16.04+2)' '--enable-nls' '--enable-integer-datetimes' '--enable-thread-safety' '--enable-tap-tests' '--enable-debug' '--enable-dtrace' '--disable-rpath' '--with-uuid=e2fs' '--with-gnu-ld' '--with-pgport=5432' '--with-system-tzdata=/usr/share/zoneinfo' '--with-llvm' '--with-systemd' '--with-selinux' 'MKDIR_P=/bin/mkdir -p' 'TAR=/bin/tar' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -pie -fno-omit-frame-pointer' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' '--with-gssapi' '--with-ldap' '--with-includes=/usr/include/mit-krb5' '--with-libs=/usr/lib/mit-krb5' '--with-libs=/usr/lib/x86_64-linux-gnu/mit-krb5' 'build_alias=x86_64-linux-gnu' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'
CC = gcc
CPPFLAGS = -I/usr/include/x86_64-linux-gnu -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/include/mit-krb5
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -pie -fno-omit-frame-pointer
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-6.0/lib -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lpthread -lselinux -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -ledit -lrt -lcrypt -ldl -lm
VERSION = PostgreSQL 11.0 (Ubuntu 11.0-1.pgdg16.04+2)
```

**Comment by za-arthur** [comment]
Hello,
Yep, this is because `pgxn` stores old version of `RUM`, 1.1.0. Current version of `RUM` is 1.3.0. For now you may try version from GitHub.
@akorotkov maintains distribution `RUM` through `pgxn`.

**Comment by levin222** [comment]
@za-arthur
When I try to install from Github 
it show that 👍 

make USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -pie -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal -I/usr/include/x86_64-linux-gnu -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o src/rumsort.o src/rumsort.c
In file included from src/rumsort.c:138:0:
/usr/include/postgresql/11/server/utils/probes.h:10:21: fatal error: sys/sdt.h: 没有那个文件或目录
compilation terminated.
<builtin>: recipe for target 'src/rumsort.o' failed
make: *** [src/rumsort.o] Error 1

**Comment by ArturFormella** [comment]
Try 
sudo apt-get install systemtap-sdt-dev

**Comment by za-arthur** [comment]
@levin222 , can you try the solution from https://github.com/postgrespro/rum/issues/27#issuecomment-336698374

**Comment by levin222** [comment]
apt install postgresql 11
by https://tecadmin.net/install-postgresql-server-on-ubuntu/

I try in 2 vps get the same error

**Comment by za-arthur** [comment]
@levin222 , did you install `postgresql-server-dev` package?

**Comment by za-arthur** [comment]
Ok. Thank you! I'll try to understand what happens here.

**Comment by za-arthur** [comment]
So it was because of renames of structures and functions in `rbtree.h` for PostgreSQL 10 and 11. See:
https://github.com/postgres/postgres/commit/b2e754c14e2741a076691e8c6f0099afffaa842e
https://github.com/postgres/postgres/commit/1f28ec6be27085819a6adfa96ba305bb4ee47f4c

I pushed a commit which fixes this. I'll ask maintainers of `RUM` apt package to update it, so it will take time to update the package. For now you can use `RUM` sources to build instead of the package.

**Comment by za-arthur** [comment]
I wrote to the PostgreSQL mailing list. So will wait:
https://www.postgresql.org/message-id/5e395595-4ab6-d95f-4666-8c9fb0a3d148%40postgrespro.ru

**Comment by ChristophBerg** [comment]
1.3.1 works with 11.1, but not with 10.6:
```
13:15:05 gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o src/rumsort.o src/rumsort.c
13:15:05 In file included from src/rumsort.c:142:
13:15:05 src/rum.h:782:2: error: unknown type name 'RBTNode'
13:15:05   RBTNode  rbnode;
13:15:05   ^~~~~~~
```

**Comment by za-arthur** [comment]
Hm, interesting. It seems REL_10_6 didn't get those renames, but REL_11_1 got. Maybe REL_10_7 will have different names in rbtree.h, so it is necessary to handle 10.6 and future 10.7 differently.

**Comment by ChristophBerg** [comment]
Fwiw, if you are pushing out an update, tag it as 1.3.2, 1.3.1 has already been uploaded to Debian.

**Comment by za-arthur** [comment]
Yes, I pushed recently tag 1.3.2. It is fixed there.
Thank you!

**Comment by ChristophBerg** [comment]
I just checked the PG git tree, 10.7 will indeed have the renames. The renames were meant to be part of 11.2, but due to the "emergency" disabling of the recheck_on_update optimizations, 11.1 got re-tagged so that commit slipped in. Duh.

**Comment by za-arthur** [comment]
`postgresql-10-rum` and `postgresql-11-rum` packages were updated. Close the issue.
